# Site settings
title: PhysicBox for iOS
email: physicbox@gmail.com
description: "PhysicBox. The Best iOS App For Your Physic Work."
url: "http://physic-box.com"
itunes-link: "https://itunes.apple.com/lu/app/physicbox/id918492603?mt=8"

# Build settings
markdown: kramdown
permalink: pretty
